from math import pi, sqrt

SVG_SIZE = 1200
N = 16
TN = 6

WIDTH = (SVG_SIZE*0.9)/2/N
SCALE_Y = sqrt(0.75)*2
HEIGHT = WIDTH*SCALE_Y
TRIANGLE_WIDTH = WIDTH * N
TRIANGLE_HEIGHT = (HEIGHT * (N+1)) / 2

INITIAL_ANGLE = pi/2
